name: CI for Qt Project with GUI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt translation tools
      run: sudo apt-get install qttools5-dev-tools
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Set up Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
        libqt5widgets5 libqt5gui5 libqt5sql5 libqt5sql5-psql \
        libgl1-mesa-dev libgl1-mesa-glx postgresql-client \
        xauth x11-apps

    - name: Build the Qt project
      run: |
        qmake ONIT.pro
        make
        
    - name: Run the Qt application
      run: |
        ./ONIT -platform offscreen
